version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu

hooks:
  ApplcationStop:
    - location: ./codedeploy_scripts/applicationStop.sh
      timeout: 300

  AfterInstall:
    - location: ./codedeploy_scripts/afterInstall.sh
      timeout: 300

  ApplicationStart:
    - location: ./codedeploy_scripts/applicationStart.sh
      timeout: 300 