version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
  build_deploy:
    jobs:
    - build
