version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy: 
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout        
      - run:
          name: Updating apt-get
          command: sudo apt-get update
      - run:
          name: Installing wget
          command: 'sudo apt-get install wget zip unzip'
      - run:
          name: Installing aws cli
          command: sudo pip install awscli
      - run:
          name: Creating the web app artifact
          command: |
            aws configure set default.region us-east-1
            touch ipadd.txt
            sudo echo IP_ADDRESS=${IP_ADDRESS} >> ipadd.txt
            touch ipaddress.txt
            sudo echo ${IP_ADDRESS} >> ipaddress.txt
            mkdir -p webapp_zip
            zip -r webapp-${CIRCLE_BUILD_NUM}.zip ./
            mv webapp-${CIRCLE_BUILD_NUM}.zip webapp_zip/
            
      - run:
          name: Uploading artifact to S3 bucket 
          command: |
            aws s3 cp webapp_zip/webapp-${CIRCLE_BUILD_NUM}.zip s3://${S3_BUCKET_NAME} 
      - run:
          name: AWS CodeDeploy call
          command: |
            aws deploy register-application-revision --application-name csye6225-webapp --s3-location bucket=${S3_BUCKET_NAME},bundleType=zip,key=webapp-${CIRCLE_BUILD_NUM}.zip
            aws deploy create-deployment --application-name csye6225-webapp --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${S3_BUCKET_NAME},bundleType=zip,key=webapp-${CIRCLE_BUILD_NUM}.zip --deployment-config-name CodeDeployDefault.AllAtOnce 
workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
  build_deploy:
    jobs:
    - build
    - deploy